@echo off
echo Setting password...
set PGPASSWORD=password
echo Running UPDATE command...
"C:\Program Files\PostgreSQL\16\bin\psql.exe" -h localhost -U postgres -d sefinal -c "UPDATE users SET role = 'ADMIN' WHERE id = 8;"
echo Running SELECT command...
"C:\Program Files\PostgreSQL\16\bin\psql.exe" -h localhost -U postgres -d sefinal -c "SELECT id, email, role FROM users WHERE id = 8;"
echo Done.
